group: rxnbench_vqa
task: rxnbench_vqa_zh
dataset_path: UniParser/RxnBench
dataset_name: RxnBench-VQA
test_split: zh
output_type: generate_until
doc_to_visual: !function utils_zh.rxnbench_doc_to_visual
doc_to_text: !function utils_zh.rxnbench_doc_to_text
doc_to_target: !function utils_zh._get_target
generation_kwargs:
  max_new_tokens: 10
  temperature: 0
  do_sample: false
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
process_results: !function utils_zh.rxnbench_process_results
metadata:
  - version: 1.0
    language: zh
    license: cc-by-nc-4.0
    task_categories: [visual-question-answering]
    tags: [chemistry]

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\n请根据图像和问题，从以上四个选项中选择最合适的答案。\n只输出单个字母 (A, B, C 或 D)，不要输出选项内容，也不要输出任何解释。"
