dataset_path: "json"
dataset_kwargs:
  data_files:
    test: "tsynbio/ProteinLMBench"

task: "ProteinLMBench"
test_split: "test"
output_type: "generate_until"

doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target

generation_kwargs:
  max_new_tokens: 32
  temperature: 0.0
  do_sample: false

process_results: !function utils.process_results

metric_list:
  - metric: protein_lm_accuracy
    aggregation: mean
    higher_is_better: true
