dataset_path: "InnovatorLab/MolParse"
task: "MolParse"
test_split: "test"
output_type: "generate_until"

doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target

generation_kwargs:
  max_new_tokens: 256
  temperature: 0.0
  top_p: 1.0
  num_beams: 1
  do_sample: false

process_results: !function utils.process_results

metric_list:
  - metric: api_judge_accuracy
    aggregation: !function utils.aggregation
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  - version: 1.0
