task: smol_name_conversion-s2i
dataset_path: json
dataset_kwargs:
  data_files:
    train: name_conversion-s2i.jsonl # 修改为对应路径

output_type: generate_until
test_split: train

doc_to_visual: !function utils.smol_doc_to_visual
doc_to_text: !function utils.smol_doc_to_text
doc_to_target: !function utils.smol_doc_to_target

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0.0
  do_sample: false

process_results: !function utils.smol_process_results

metric_list:
  - metric: smol_metrics
    aggregation: !function utils.smol_aggregate_results
    higher_is_better: true
